# Generated by Django 4.2.7 on 2023-12-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_Code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('Capital_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Capital_Name', models.CharField(max_length=100)),
                ('Country_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
