# Generated by Django 4.2.7 on 2023-12-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='Country_Code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='Country_Code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
