# Generated by Django 4.2.7 on 2023-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_capital_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capital',
            name='Capital_ID',
        ),
        migrations.RemoveField(
            model_name='country',
            name='Currency',
        ),
        migrations.AddField(
            model_name='capital',
            name='Currency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capital',
            name='Capital_Name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
